FROM registry.tech.hextech.io/library/node:17.5-alpine as builder
# ARG GRPC_TOOLS_BINARY=https://metazen-development-support-singapore.s3.ap-southeast-1.amazonaws.com/ <-- Not needed here
ARG TARGETPLATFORM
ARG NPM_REGISTRY_CONFIGURATION
ARG ENVIRONMENT
ARG REGISTRY_HOST
ARG PROJECT_ID
ARG AUTH_TOKEN

WORKDIR /app

COPY . .

RUN echo ${NPM_REGISTRY_CONFIGURATION} | base64 -d > ~/.npmrc
RUN cat ~/.npmrc
RUN npm ci --ignore-scripts


## REACT BUILD VARS ---------------------- ##
ARG REACT_APP_VERSION="$npm_package_version"
ARG REACT_APP_WITH_DEMO="true"
ARG REACT_APP_USE_MAINNET="false"
ARG REACT_APP_DEFAULT_NETWORK_VERSION="80001"
ARG REACT_APP_NODE_PROVIDER='{"4":"https://eth-rinkeby.nodereal.io/v1/bf5309c62fad4bc58260171741c5e67b","5":"https://eth-goerli.nodereal.io/v1/4c3daa18bf0b4b6b80373b8d6d26d84f","80001":"https://small-green-breeze.matic-testnet.quiknode.pro/fbd755dbab8669355c48e512cee494083ff6673f"}'
ARG REACT_APP_ETHER_SCAN_APIKEY="X8HJYMS93W35AUGQA2K8FEAA25PFTY7NIH"

ARG REACT_APP_METAZENS_API="/api"
ARG REACT_APP_METAZENS_WALLET_API="/api"
ARG REACT_APP_METAZENS_MFA_API="/api/mfa"
ARG REACT_APP_METAZENS_MFA_PAGE_URL="/api/mfa/login"
ARG REACT_APP_METAZENS_TXBUILDER_API="/api"
ARG REACT_APP_METAZENS_BOOKKEEPING_API="/api"
ARG REACT_APP_METAZENS_TXHISTORY_API="/api"
ARG REACT_APP_METAZENS_ASSET_MASTER_API="/api"
ARG REACT_APP_METAZENS_ASSET_EVALUATOR_API="/api"
ARG REACT_APP_GRYFYN_KYC_API="/api"
ARG REACT_APP_METAZENS_ASSET_METADATA_CACHE_API="/api"
ARG REACT_APP_METAZENS_USER_SERVICE_API="/api"
ARG REACT_APP_KYC_API_URL="/api/kyc/api/v1"

# Reference: https://medium.com/swlh/reactjs-docker-environment-variables-f35eb591683e
RUN REACT_APP_VERSION=${REACT_APP_VERSION} \
        REACT_APP_USE_MAINNET=${REACT_APP_USE_MAINNET} \
        REACT_APP_WITH_DEMO=${REACT_APP_WITH_DEMO} \
        REACT_APP_DEFAULT_NETWORK_VERSION=${REACT_APP_DEFAULT_NETWORK_VERSION} \
        REACT_APP_NODE_PROVIDER=${REACT_APP_NODE_PROVIDER} \
        REACT_APP_ETHER_SCAN_APIKEY=${REACT_APP_ETHER_SCAN_APIKEY} \

        REACT_APP_METAZENS_API=${REACT_APP_METAZENS_API} \
        REACT_APP_METAZENS_WALLET_API=${REACT_APP_METAZENS_WALLET_API} \
        REACT_APP_METAZENS_MFA_API=${REACT_APP_METAZENS_MFA_API} \
        REACT_APP_METAZENS_MFA_PAGE_URL=${REACT_APP_METAZENS_MFA_PAGE_URL} \
        REACT_APP_METAZENS_TXBUILDER_API=${REACT_APP_METAZENS_TXBUILDER_API} \
        REACT_APP_METAZENS_BOOKKEEPING_API=${REACT_APP_METAZENS_BOOKKEEPING_API} \
        REACT_APP_METAZENS_TXHISTORY_API=${REACT_APP_METAZENS_TXHISTORY_API} \
        REACT_APP_METAZENS_ASSET_MASTER_API=${REACT_APP_METAZENS_ASSET_MASTER_API} \
        REACT_APP_METAZENS_ASSET_EVALUATOR_API=${REACT_APP_METAZENS_ASSET_EVALUATOR_API} \
        REACT_APP_GRYFYN_KYC_API=${REACT_APP_GRYFYN_KYC_API} \
        REACT_APP_METAZENS_ASSET_METADATA_CACHE_API=${REACT_APP_METAZENS_ASSET_METADATA_CACHE_API} \
        REACT_APP_METAZENS_USER_SERVICE_API=${REACT_APP_METAZENS_USER_SERVICE_API} \
        REACT_APP_KYC_API_URL=${REACT_APP_KYC_API_URL} \
        npm run build


FROM --platform=$TARGETPLATFORM registry.tech.hextech.io/library/nginx:1.21-alpine
ENV USR=nginx
ARG PORT=80

RUN chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d && \
        chown -R nginx:nginx /var/run/
RUN chmod -R 777 /etc/nginx/conf.d

COPY --chown=nginx:nginx --from=builder /app/build /usr/share/nginx/html
# RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE $PORT
