FROM registry.tech.hextech.io/library/nginx:1.21-alpine
ENV USR=nginx
ARG PORT=80

RUN chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d && \
        chown -R nginx:nginx /var/run/
RUN chmod -R 777 /etc/nginx/conf.d

COPY --chown=nginx:nginx build /usr/share/nginx/html
# RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE $PORT
