import NftAssetMetadata from './NftAssetMetadata';

export const defaultNftAssetMetadata: NftAssetMetadata = {
  symbol: '',
  chainId: '',
  contractAddress: '',
  owner: '',
  tokenId: '',
  tokenStandard: '',
  createdTime: '',
  updatedTime: '',
  data: {
    attributes: [],
    class: '',
    collection: '',
    core: {
      acceleration: '',
      chassisNumber: '',
      class: '',
      collection: '',
      handling: '',
      item: '',
      livery: '',
      manufacturer: '',
      nfFlag: '',
      rarity: '',
      topSpeed: '',
      type: '',
      weight: '',
      year: '',
    },
    description: '',
    external_url: '',
    id: '',
    image: '',
    manufacturer: '',
    name: '',
    racing_acceleration: 0,
    racing_handling: 0,
    racing_topSpeed: 0,
    rarity: '',
    type: '',
    year: 2000,
  },
};
